### ISSUE TITLE
No pdf created after running Python script (Mac OS) 

### ISSUE THREAD

**Issue by Haochen92** [AlJohri/docx2pdf#13]
![image](https://user-images.githubusercontent.com/50657634/84469102-e129f180-acb2-11ea-90af-149fe9d721f2.png)

Basically, when tried converting the file from cmd line or using my python script, there was no pdf output. I'm quite new to programming so I wonder if you will be able to find out what is the problem. 
I was wondering if it's cause I did not grant permission when this popped up :bash would like to control system events

**Comment by Haochen92** [comment]
After granting permission, it worked. Thanks

**Comment by chenxi2015** [comment]
> 

How did you solve it? Can you tell me

**Comment by chenxi2015** [comment]
> After granting permission, it worked. Thanks

How did you solve it? Can you tell me
