### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by woutkonings** [AlJohri/docx2pdf#18]
Hi!

I have some problems installing the package. It seems to try to install docx2pdf and appscript at the same, while appscript is already installed.

Terminal log:

`pip install docx2pdf `
`Collecting docx2pdf`
`Using cached docx2pdf-0.1.7-py3-none-any.whl (6.6 kB)`
`Collecting appscript<2.0.0,>=1.1.0; sys_platform == "darwin"`
 `Using cached appscript-1.1.1-cp37-cp37m-macosx_10_6_x86_64.whl (83 kB)`
`Requirement already satisfied: importlib_metadata<2.0.0,>=1.3.0; python_version < "3.8" in /opt/anaconda3/lib/python3.7/site-packages (from docx2pdf) (1.5.0)`
`Requirement already satisfied: tqdm<5.0.0,>=4.41.0 in /opt/anaconda3/lib/python3.7/site-packages (from docx2pdf) (4.42.1)`
`Requirement already satisfied: zipp>=0.5 in /opt/anaconda3/lib/python3.7/site-packages (from importlib_metadata<2.0.0,>=1.3.0; python_version < "3.8"->docx2pdf) (2.2.0)`
`Installing collected packages: appscript, docx2pdf`
  `Attempting uninstall: appscript`
    `Found existing installation: appscript 1.0.1`
`ERROR: Cannot uninstall 'appscript'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

**Comment by AlJohri** [comment]
@woutkonings, it appears pip wants to uninstall your currently installed version of appscript at `1.0.1` and replace it with appscript `1.1.1`.

the best solution here to use a virtual environment. if you're on python3, you can run:

```
python3 -m venv venv
source venv/bin/activate
pip install docx2pdf
```

here's some docs on venv in case you need more help: https://docs.python.org/3/library/venv.html

**Comment by AlJohri** [comment]
Closing this issue for now but please feel free to ping me here if you need more help.
