### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by boehmc** [AlJohri/docx2pdf#2]
Hi @AlJohri , thanks for this awesome package! That's really useful.

The package is listed with MIT on [pypi](https://pypi.org/project/docx2pdf/), but I don't see it here. Would you mind adding a license to the repo?

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by AlJohri** [comment]
@boehmc done, thanks!
