### ISSUE TITLE
Any roadmap or library enhancement for Linux machines ?

### ISSUE THREAD

**Issue by multinucliated** [AlJohri/docx2pdf#22]
Can we use this library in Linux environment?

**Comment by micahcochran** [comment]
Similar to #11

**Comment by AlJohri** [comment]
linux isn't actively supported at this time but I'm open to pull requests

we can implement this via libreoffice as described in #11. I've also heard reports that it worked with "WPS Office" on Linux from @RDxR10

closing in favor of #11 for now, happy to continue the conversation there
