### ISSUE TITLE
generate password protected pdf file

### ISSUE THREAD

**Issue by jurajsucik** [AlJohri/docx2pdf#25]
this is a request to add a new feature that would allow to generate password protected pdf file.

**Comment by AlJohri** [comment]
I don't think there's an option in Microsoft Word to save a document as a PDF with a password on both Windows or MacOS.

<img width="919" alt="Screen Shot 2021-01-07 at 3 40 47 PM" src="https://user-images.githubusercontent.com/2790092/103942657-ba278700-50fe-11eb-9b37-3670c81ae619.png">

As this program relies on Word to make the changes such a feature would have to be implemented as a post-processing step in which case it probably makes more sense to implement outside of this tool.

Sources:

- https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_mac-mso_2019/how-do-i-save-a-word-doc-to-password-protected-pdf/e16efdd2-03e7-4c90-828f-dab462dca5ee
- https://docs.microsoft.com/en-us/office/vba/api/word.saveas2

**Comment by AlJohri** [comment]
Closing this issue but feel free to continue the conversation if there's any changes that need to be made to docx2pdf!

**Comment by jurajsucik** [comment]
I understand. In that case it, are you able to add this as a post-processing step?
