### ISSUE TITLE
DocxToPdf not supported in Python 3.9.4

### ISSUE THREAD

**Issue by ccastanoG** [AlJohri/docx2pdf#34]
I was using this library for convert my docx files to pdf, but the requirements of virtual machine where is running the scirpt now are differents, i need to use the version 3.9.4 of python and the library dont support this. its near a new update for support it?
thanks

**Comment by AlJohri** [comment]
@ccastanoG can you tell me what error occurred?

**Comment by AlJohri** [comment]
This should be fixed now in #48.
