### ISSUE TITLE
Attribute.Error : Word.Application.Documents

### ISSUE THREAD

**Issue by Orsobrugno** [AlJohri/docx2pdf#37]
Hello there,
I am pretty new to Python and I was working on a simple script to convert all word file in a folder. The script kind of works, meaning that sometimes I get the error I mentionend in the title, I do not know if it is random or there's something wrong with my code (which I attach).
[Stampa_PDF.txt](https://github.com/AlJohri/docx2pdf/files/6968722/Stampa_PDF.txt)
Besides, every time I use it and it works it show 1 progress string empty and 1 progress string with the actual percentage of the process.
Could someone help me? 
Thanks

**Comment by AlJohri** [comment]
related to #29 or #32

**Comment by AlJohri** [comment]
@Orsobrugno I think you want to use the [tqdm](https://github.com/tqdm/tqdm) library around your loop. since the `convert` function is only being called with a single file, it has no notion of the full progress of your loop
