### ISSUE TITLE
docx2pdf doesn't preserve any links in the final pdf on Mac

### ISSUE THREAD

**Issue by aeltanawy** [AlJohri/docx2pdf#38]
I'm using docx2pdf to do a bulk conversion from docx to pdf and it looks like the final pdf, while it is preserving the link font styling, the hyperlink itself is gone. This is only observed on Mac as when I run the same script on a Windows machine, everything is working as expected.

If it is at all useful, I'm using docx2pdf v.0.1.7, Python v.3.8.2, word v.16.51, and Mac v.11.5.1

**Comment by AlJohri** [comment]
I don't have a solution for you but this might be the underlying issue from Issue https://github.com/AlJohri/docx2pdf/issues/30 which revolved around TOC links.

**Comment by AlJohri** [comment]
On further reading, yeah I think this issue is identical. If you have the time, I'd love to hear if any of the potential solutions described here work for your use case: https://github.com/AlJohri/docx2pdf/issues/30#issuecomment-815811946

**Comment by aeltanawy** [comment]
For real @AlJohri  ! I tried haakonstorm solution [here](https://github.com/AlJohri/docx2pdf/issues/30#issuecomment-813604480) and now the pdf has the full links! Changing this option once with saving as a pdf preserves the choice for any subsequent savings as a pdf event so this resolves the issue!

Thanks for looking into it!
