### ISSUE TITLE
Issues with running on 64 bit machine?

### ISSUE THREAD

**Issue by Juliette1110** [AlJohri/docx2pdf#39]
I'm trying to batch convert some .docx files and am running the program on Jupyter notebook (5.7.4) I do have a 64-bit laptop and the errors reference 32 bit so I'm afraid this program might not work on it. Has anyone on a 64-bit machine had luck running it? 
Code:

!pip install ipywidgets
!pip install docx2pdf
from docx2pdf import convert
convert(r"C:\Users\Juliette\Documents\Other\Other")

Which returns the following error:
![image](https://user-images.githubusercontent.com/47187446/131190469-d08f73cb-86f5-4aaa-8755-396b3d955272.png)

**Comment by AlJohri** [comment]
hi @Juliette1110, the reference to `win32api` does not relate to 32-bit vs 64-bit. I believe you are running into this anaconda specific issue: https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

hope that points you in the right direction

**Comment by Juliette1110** [comment]
Yep, that helped! There were a few other issues on my end but now it works great--thanks for publishing this awesome program!!
