### ISSUE TITLE
python 3.9.5 is not supported

### ISSUE THREAD

**Issue by GGunnison** [AlJohri/docx2pdf#40]
I am trying to convert a docx file using python 3.9.5 and I'm getting this error:   0%|                                                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]{'input': '/Users/username/Filename.docx', 'output': '/Users/username/output.pdf', 'result': 'error', 'error': 'Error: An error occurred.'}
  0%|                                                                                                                                                                                                  

Any chance you could help? Happy to also go back to a version of python that is supports for now, until we get a different templating engine running

**Comment by AlJohri** [comment]
I'm not sure if this is a python version issue. if it is, see #48. this seems like an intermittent issue that occurs when word is already open before running the script.

please re-open the issue and attach a failing doc if the error persists
