### ISSUE TITLE
new Window/Document instead of activeDocument

### ISSUE THREAD

**Issue by Inqnuam** [AlJohri/docx2pdf#43]
Thanks for this very useful script!
Just noticed that running the script while we are working on a document on Microsoft Word will close our document window.
Could you please open the printing document inside a new window/document so we will dont lose our work?
Thank you again

**Comment by AlJohri** [comment]
I'm not entirely sure if this is possible.

Assuming you're on windows, as you can see in the below snippet:

https://github.com/AlJohri/docx2pdf/blob/40169f76611ce4412f9e1669b56521bdfafae395/docx2pdf/__init__.py#L25-L27

The snippet is opening a document rather than relying on an "active" document. I think its best to just not actively have word open / use word during the conversion.

**Comment by Inqnuam** [comment]
> I'm not entirely sure if this is possible.
> 
> Assuming you're on windows, as you can see in the below snippet:
> 
> https://github.com/AlJohri/docx2pdf/blob/40169f76611ce4412f9e1669b56521bdfafae395/docx2pdf/__init__.py#L25-L27
> 
> The snippet is opening a document rather than relying on an "active" document. I think its best to just not actively have word open / use word during the conversion.

The issue is related to macOS so on JSX side of the code

**Comment by AlJohri** [comment]
Got it. Attaching the relevant macOS snippet below. I see that it is indeed using `activeDocument`.

https://github.com/AlJohri/docx2pdf/blob/40169f76611ce4412f9e1669b56521bdfafae395/docx2pdf/convert.jxa#L131-L134

Doing a quick google search on other applescript and JXA implementations, it seems others are also relying on the "active document". I'm not sure if there's an alternative here.

links:
- https://discussions.apple.com/thread/250068127?answerId=250120146022#250120146022
- https://developer.apple.com/forums/thread/117382

**Comment by Inqnuam** [comment]
> Got it. Attaching the relevant macOS snippet below. I see that it is indeed using `activeDocument`.
> 
> https://github.com/AlJohri/docx2pdf/blob/40169f76611ce4412f9e1669b56521bdfafae395/docx2pdf/convert.jxa#L131-L134
> 
> Doing a quick google search on other applescript and JXA implementations, it seems others are also relying on the "active document". I'm not sure if there's an alternative here.
> 
> links:
> 
> * https://discussions.apple.com/thread/250068127?answerId=250120146022#250120146022
> * https://developer.apple.com/forums/thread/117382

What if we duplicate opening file into tmp directory then remove it after converting?
