### ISSUE TITLE
AssertionError: Line 89 in __init__.py

### ISSUE THREAD

**Issue by CSynodinos** [AlJohri/docx2pdf#46]
Hi,

I have been using your library to do multiple file conversions, but I run into an AssetionError when I tried to convert a .doc file.

By reading your code, it's pretty clear that only .docx files are acceptable input arguments. Is it possible to add .doc support as well?

Edit: Saw that there is another issue thread made a year ago. Is .doc support still planned?

Thank you

**Comment by AlJohri** [comment]
@CSynodinos I haven't had time to add support for `.doc` but would be happy to accept a PR to do so!

**Comment by AlJohri** [comment]
Closing as duplicate of #4
