### ISSUE TITLE
Attribute Error : Open.SaveAs when converting a word doc to pdf

### ISSUE THREAD

**Issue by SirishaGorasa** [AlJohri/docx2pdf#49]
I have installed docx2pdf as:

> pip install docx2pdf

I am trying to convert a word document to PDF  with the below code:
``from docx2pdf import convert``
``convert("secrecy.docx", "My_Files\\output.pdf")``

I am facing the below error :
![image](https://user-images.githubusercontent.com/47634813/143821273-bf432d69-fbfb-45b6-ab8f-de6d3396fb03.png)

I am unable to figure out the underlying issue i.e, why this error is being occurred.

Is this the problem with my python version? I am using Python 3.8.3. Could you please let me know the solution for this as early as possible?

**Comment by AlJohri** [comment]
could be similar to this issue? https://github.com/AlJohri/docx2pdf/issues/21

**Comment by AlJohri** [comment]
@SirishaGorasa closing the issue for now. please feel to re-open and add a sample document to help me  reproduce the issue
