### ISSUE TITLE
exit() call in library code not working 

### ISSUE THREAD

**Issue by jack-rory-staunton** [AlJohri/docx2pdf#6]
From jupyter the code breaks at line 73 

exit(1)

with the following traceback:

NameError                                 Traceback (most recent call last)
<ipython-input-9-61338add51e3> in <module>
----> 1 convert('./BAAM_raw/docx/', './BAAM_raw/docx/pdf/')

/usr/local/lib/python3.7/site-packages/docx2pdf/__init__.py in convert(input_path, output_path, keep_active)
    102     paths = resolve_paths(input_path, output_path)
    103     if sys.platform == "darwin":
--> 104         return macos(paths, keep_active)
    105     elif sys.platform == "win32":
    106         return windows(paths, keep_active)

/usr/local/lib/python3.7/site-packages/docx2pdf/__init__.py in macos(paths, keep_active)
     70         elif msg["result"] == "error":
     71             print(msg)
---> 72             exit(1)
     73 
     74 

NameError: name 'exit' is not defined

I tried editing the import with:

from sys import exit

but this does not change anything.

**Comment by AlJohri** [comment]
thanks for reporting @jack-rory-staunton. I'll push a fix soon

**Comment by AlJohri** [comment]
@jack-rory-staunton I just pushed version 0.1.7, can you try it out?

**Comment by jack-rory-staunton** [comment]
thanks for your quick reaction - I'm running it now, I will let you know how it goes!

**Comment by jack-rory-staunton** [comment]
I had previously edited that line to sys.exit(1) and it didn't fix the issue. Using 0.1.7 I get the same error (below). I think iPython handles quit/exit/sys.exit somehow differently to Python and a different workaround is required.   

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-5-4f33c014e76d> in <module>
----> 1 convert('./BAAM_raw/', './BAAM_raw/')

/usr/local/lib/python3.7/site-packages/docx2pdf/__init__.py in convert(input_path, output_path, keep_active)
    102     paths = resolve_paths(input_path, output_path)
    103     if sys.platform == "darwin":
--> 104         return macos(paths, keep_active)
    105     elif sys.platform == "win32":
    106         return windows(paths, keep_active)

/usr/local/lib/python3.7/site-packages/docx2pdf/__init__.py in macos(paths, keep_active)
     70         elif msg["result"] == "error":
     71             print(msg)
---> 72             sys.exit(1)
     73 
     74 

SystemExit: 1

**Comment by jack-rory-staunton** [comment]
In any case, when using the convert() function on a whole directory, it would be nice if there was a way to skip over any files that throw such exceptions (e.g. wrap in a try/except).

**Comment by jack-rory-staunton** [comment]
I tried processing the same file using the CLI and get this:

| => docx2pdf ./ ./
  0%|                                                     | 0/2 [00:00<?, ?it/s]{'input': '/Users/jrs/Documents/GitHub/nndata-research-bundle/services/BAAM_raw/ASED draft BAA 7.20.2017.docx', 'output': '/Users/jrs/Documents/GitHub/nndata-research-bundle/services/BAAM_raw/ASED draft BAA 7.20.2017.pdf', 'result': 'error', 'error': 'Error: Message not understood.'}

**Comment by AlJohri** [comment]
Got it. We can make that happen.

**Comment by reisner** [comment]
I also get the `Error: Message not understood.` -- is there any way to figure out what is causing this in the input file?

**Comment by asapsmc** [comment]
I'm also getting this error. Is there any news about this?
