### ISSUE TITLE
Images not showing in PDF

### ISSUE THREAD

**Issue by StraggleMuffin** [AlJohri/docx2pdf#64]
I'm using the batch convert(filepath) on about 40 documents with very similar layouts. However, when converting from docx to pdf the same final image, a png of a signature, turns into placeholder text. I have disabled picture placeholder in the word document options and the registry yet the issue still remains. 

This is what the image turns into: 
![image](https://user-images.githubusercontent.com/38747325/163140160-5b9d9cf1-79d0-4270-a7b3-855e5eb5e418.png)

This issue however resolves if the word documents are saved into pdf's individually hence why I regard this as an issue. Any assistance would be appreciated :)

**Comment by StraggleMuffin** [comment]
Just went into the module and rewrote some of it and it's now working with images.

**Comment by AlJohri** [comment]
Awesome @StraggleMuffin ! Can you submit a pull request with those changes? Or share a `git diff` of how you fixed this for the next person that runs into this issue?

**Comment by StraggleMuffin** [comment]
Not really sure how to do that I've not used github before. But I just implemented a "time delay" using time.sleep(time_delay) where I set it at 0.5 seconds for the number of images I had per document. Sorry on not being able to be more helpful
