### ISSUE TITLE
Is there a way to disable the progress bar?

### ISSUE THREAD

**Issue by genteelmagpie** [AlJohri/docx2pdf#71]
Hello, 

  I am using this to convert many files in a go and I am using my own progressbar. Is there a way I can disable the progress bar docx2pdf shows while converting files to pdf ?

**Comment by AlJohri** [comment]
unfortunately not at the moment, but this would be a welcome feature

**Comment by genteelmagpie** [comment]
@AlJohri 

It would be a big help if you add it in a future update. I really use 'docx2pdf' on a daily basis. I am a student so you can imagine the need. The conversions are amazing and I am enjoying your work a lot. 

Thanks for sharing your hard work.
