### ISSUE TITLE
convert a whole folder to pdf drops error

### ISSUE THREAD

**Issue by frondoto** [AlJohri/docx2pdf#9]
hi, im just using this two lines in the whole script
```
from docx2pdf import convert

convert("encontrados/")
```
and the library converts a random ammount of .docx to .pdf and drops this error

> com_error: (-2147418111, 'La llamada fue rechazada por el destinatario.', None, None)

i've tried using different versions of the library and it still doing the same. Do you think its a library issue?
Thanks

**Comment by AlJohri** [comment]
@frangamba I tried googling "com_error: (-2147418111" and seems like it might be related to having a file/folder open. can you check if you have explorer or word open?

**Comment by Burd89** [comment]
Similar error here "com_error: (-2147352567, 'Er is een uitzondering opgetreden.', (0, 'Microsoft Word', 'The file appears to be corrupted.', 'wdmain11.chm', 25272, -2146822496), None)".

Closing explorer did not help.

**Comment by AlJohri** [comment]
@Burd89 I think that's a slightly different error as it says "The file appears to be corrupted". Does the fiel open in MS Word normally? Do you get that same error (w/ same error code) with using a different file?

------------------------

Leaving a note for myself to check when I'm back on my windows laptop:

```
import win32api
print(win32api.FormatMessage(-2147418111))
print(win32api.FormatMessage(-2147352567))
```

ref: https://stackoverflow.com/questions/36064723/pywintypes-com-error-2147352567-exception-occurred-0-none-none-none

**Comment by Burd89** [comment]
The files open normally in word. I only get the error when converting the whole folder. No errors are given when converting the files separately. Which is fine for now

**Comment by ayushkoul33** [comment]
File "<COMObject <unknown>>", line 8, in Open
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Word', 'The file appears
to be corrupted.', 'C:\\Program Files (x86)\\Microsoft Office\\Office12\\1033\\WDMAIN11.CHM', 25272, -2146822496), None)

For Separate conversion of single docx file ,I am getting the above error of file is corrupted.. how to fix it??
